version: '3.1'
services: 
  db:
    container_name: labtracker_postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: labtracker
      POSTGRES_PASSWORD: labtracker
      POSTGRES_DB: labtracker
    ports:
        - "5432:5432"