version: '3.1'
services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    cap_add: [ 'SYS_PTRACE' ]
    environment:
      - "ACCEPT_EULA=1"
      - "MSSQL_SA_PASSWORD=SU2orange!"
    ports:
      - "127.0.0.1:1433:1433"
      - "127.0.0.1:1401:1401"
      - "127.0.0.1:1431:1431"
    hostname: mssql